### ISSUE TITLE
能否添加热重载的功能

### ISSUE THREAD

**Issue by chenxi-Eumenides** [lgc2333/nonebot-plugin-autoreply#1]
## 新功能建议

添加热重载或者自动重载配置文件，改一次重启一下qqbot有点麻烦

**Comment by lgc2333** [comment]
更新了，欢迎使用~

**Comment by HFYGitHub** [comment]
> 更新了，欢迎使用~

如何触发热重载呢

**Comment by lgc2333** [comment]
> > 更新了，欢迎使用~
> 
> 如何触发热重载呢

![image](https://github.com/lgc-NB2Dev/nonebot-plugin-autoreply/assets/59048777/07fc4695-c3de-4248-970b-008243034200)

**Comment by XieXiLin2** [comment]
看看 README
发送指令 指令前缀 + `重载自动回复`

**Comment by HFYGitHub** [comment]
> > > 更新了，欢迎使用~
> > 
> > 
> > 如何触发热重载呢
> 
> ![image](https://private-user-images.githubusercontent.com/59048777/315883727-07fc4695-c3de-4248-970b-008243034200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODEyMTQsIm5iZiI6MTcxMTA4MDkxNCwicGF0aCI6Ii81OTA0ODc3Ny8zMTU4ODM3MjctMDdmYzQ2OTUtYzNkZS00MjQ4LTk3MGItMDA4MjQzMDM0MjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA0MTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MThjYzYxMTg5NzNjNTRhNzMwY2MzNmY4OGQ0ZTExYzRhOGM1NWNiNGEzOWE5MzllNjRkNzk2NTg5NzcyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W4nHfM3uAsDgV5n68VFSRRO2bOjG7pth_KV9AX1BO-I)

hh习惯了指令是/xx形式，在readme找半天硬是没发现这个
