### ISSUE TITLE
自动回复会引用{reply}中的消息

### ISSUE THREAD

**Issue by kqcoxn** [lgc2333/nonebot-plugin-autoreply#12]
入题，当一个群友回复另一个群友时，插件好像会将回复的原消息和回复的消息合并起来检测
可不可以加入是否检测原消息的选项qwq

**Comment by lgc2333** [comment]
来张情况发生时的聊天截图，和对应的回复配置

**Comment by kqcoxn** [comment]
检查了一下回复配置，是我的配置有问题，插件并没有问题，非常抱歉QAQ
