### ISSUE TITLE
单个回复内无法换行

### ISSUE THREAD

**Issue by Wangrry97** [lgc2333/nonebot-plugin-autoreply#14]
写配置插件的过程中，发现在单个reply中无法使用\n进行换行。
仔细阅读了插件的文档，发现没有相关的信息。
![7077ed40e57e8181e7d7a5da7a31742c](https://github.com/lgc-NB2Dev/nonebot-plugin-autoreply/assets/54696128/44c62f78-7606-41cd-b088-78c8448bb168)
![4e08987cf66f312d0faae9a88b576c41](https://github.com/lgc-NB2Dev/nonebot-plugin-autoreply/assets/54696128/f51b7a33-16ee-4644-9cb8-097fbd8452a7)

**Comment by lgc2333** [comment]
仔细阅读yml教程
