### ISSUE TITLE
请问文本如何换行

### ISSUE THREAD

**Issue by HFYGitHub** [lgc2333/nonebot-plugin-autoreply#19]
尝试 \n 没效果

**Comment by lgc2333** [comment]
#9
#14

**Comment by lgc2333** [comment]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-autoreply/assets/59048777/af337fe4-2d3e-4173-b96a-4d86b5f72e36)  
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-autoreply/assets/59048777/a21df852-8ddc-4b2a-9513-4fbedaec7a5a)  
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-autoreply/assets/59048777/37577a96-9d86-4324-a3de-1d2f13e92fd6)

**Comment by HFYGitHub** [comment]
好的，已解决，使用 |和>
