### ISSUE TITLE
请问一下 0.2.0版本是不再支持多个match了吗

### ISSUE THREAD

**Issue by MerCuJerry** [lgc2333/nonebot-plugin-autoreply#3]
RT 今天在bot上部署插件的时候发现多个match的回复匹配不上了 0.2.0版本是不再支持多个match了吗

**Comment by lgc2333** [comment]
可能是bug, 稍后排查

**Comment by MerCuJerry** [comment]
读了一遍代码发现 TypeVarTuple 是 Python 3.11的特性来着 应该是我环境的问题 我换成3.11试试

**Comment by MerCuJerry** [comment]
换了3.11 还是有同样的问题
