### ISSUE TITLE
我该如何匹配仅@的选项？

### ISSUE THREAD

**Issue by QAQQL** [lgc2333/nonebot-plugin-autoreply#8]
如题，我想机器人匹配@机器人的消息（不带任何文本的），我尝试过
`
- type: fuzzy
  match: ''
  to_me: true
`
但这没有效果

**Comment by YYY-919** [comment]
通过正则匹配消息可以，但是@消息似乎不生效
```
#发所有图片的链接，需0.2.10版本
match: 'CQ:image(.+?)url=(?P<url>.*?)]'
type: regex
to_me: false,
ignore_case: true
strip: true
allow_plaintext: false
......
replies:
    - "图：{url}"
```
匹配图片都可以，但是用`[CQ:at,qq=bot的QQ号]`来模糊匹配都不行
```
#这些不生效
match: "[CQ:at,qq=bot的QQ号]"
type: fuzzy
to_me: false
ignore_case: true
strip: true
allow_plaintext: false
```
暂时不知道是什么原因（

**Comment by lgc2333** [comment]
借鉴下这个？https://autoreply.lgc2333.top/#/market/replies/are_you_here

**Comment by lgc2333** [comment]
> 通过正则匹配消息可以，但是@消息似乎不生效
> 
> ```
> #发所有图片的链接，需0.2.10版本
> match: 'CQ:image(.+?)url=(?P<url>.*?)]'
> type: regex
> to_me: false,
> ignore_case: true
> strip: true
> allow_plaintext: false
> ......
> replies:
>     - "图：{url}"
> ```
> 
> 匹配图片都可以，但是用`[CQ:at,qq=bot的QQ号]`来模糊匹配都不行
> 
> ```
> #这些不生效
> match: "[CQ:at,qq=bot的QQ号]"
> type: fuzzy
> to_me: false
> ignore_case: true
> strip: true
> allow_plaintext: false
> ```
> 
> 暂时不知道是什么原因（

可能是ob11适配器会自动删除消息头部 @机器人 的消息段的锅？

**Comment by QAQQL** [comment]
- match: ''
      type: full
      to_me: true
      allow_plaintext: false
这个配置是可用的,感谢作者大大
